name: Build Linux binary

permissions:
  contents: write

on:
  push:
    tags:
      - "*_linux"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add GHC to PATH
        env:
          GHCUP_INSTALL_BASE_PREFIX: "/usr/local"
        run: echo "/usr/local/.ghcup/bin" >> $GITHUB_PATH

      - name: Compile asgrnxrnx
        run: |
          ghc -O2 AsgRnxRnx.hs -o asgrnxrnx
          rm -f *.hi *.o

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: asgrnxrnx
