name: Build Linux binary

permissions:
  contents: write

on:
  push:
    tags:
      - "*_linux"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Zastępujemy cały problematyczny krok curl oficjalną akcją setup-haskell
      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: 'latest' # Możesz tu wpisać konkretną wersję, np. '9.6.3'

      - name: Compile asgrnxrnx
        run: |
          ghc -O2 AsgRnxRnx.hs -o asgrnxrnx
          rm -f *.hi *.o

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: asgrnxrnx
